# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b451d76a1be438424136cdc93f3b4a9e3e72a5df9c3e6f93f843c7214035385cc43435e8cd14a51ce0dfdb2cefe5c237af74308b779a23aea52aefab62cbdd8

test:
  secret_key_base: 2a68714804a87bc4030f7d94b5dc9732762fc6b06de15d4b67d4041998908282e6551d5b55127c55578f5e2090053905371eaedef4d04c0a5cdd342c2da49bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
